# import base libraries
import sys
from pathlib import Path
import numpy as np
import pandas as pd

# link core repo folder
SCRIPT_DIR = Path(__file__).resolve()
REPO_ROOT = SCRIPT_DIR.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.append(str(REPO_ROOT))

# load model data proprocessing function and MOD-WET model class
from src.chapter1 import MOD_WET_watershed_preprocessing
from src.model_driver import MODWETModel

# Setup
watershed_name = "bear_creek" # used to define folder names and point to model input and output locations

### Part A: Preprocess Raw Input Data

# A1. Read raw DEM input data to be preprocessed
northing = np.loadtxt(REPO_ROOT / f"data/raw_input/{watershed_name}/northing.txt")                  # vector of northing values
easting = np.loadtxt(REPO_ROOT / f"data/raw_input/{watershed_name}/easting.txt")                    # vector of easting values
elev = np.loadtxt(REPO_ROOT / f"data/raw_input/{watershed_name}/elev.txt", delimiter=",")           # elevation matrix
outlet_coordinate = np.array([                                                                      # watershed outlet coordinates
    float(np.loadtxt(REPO_ROOT / f"data/raw_input/{watershed_name}/outlet_easting.txt")),
    float(np.loadtxt(REPO_ROOT / f"data/raw_input/{watershed_name}/outlet_northing.txt"))
]) 

# A2. Read meteorological foring data from CSV file
raw_met_data = pd.read_csv(Path(REPO_ROOT / f"data/raw_input/{watershed_name}/met_forcing.csv"))    # CSV file contain weather station data
station_elev = float(np.loadtxt(REPO_ROOT / f"data/raw_input/{watershed_name}/gage_elev.txt")),     # weather station elevation in meters

# A3. Define other preprocessing function inputs
plots_path = REPO_ROOT / f"plots/{watershed_name}"                                                  # where plots generated by the data processing script are saved
basin_data_path = Path(REPO_ROOT / f"data/model_input/{watershed_name}/basin_static_data.nc")       # preprocessed static basin data file location and name
met_forcing_path = Path(REPO_ROOT / f"data/model_input/{watershed_name}/met_forcing.nc")            # preprocessed met forcing data file location and name

# A4. preprocess the data and save as NetCDF files
MOD_WET_watershed_preprocessing(easting=easting, northing=northing, elev=elev, outlet_coordinate=outlet_coordinate,
                                static_data_file=basin_data_path, met_data=raw_met_data, gage_elev=station_elev, 
                                met_data_file=met_forcing_path, shade_calc_flag=False, 
                                develop_plots=False, display_plots=False, plots_path=plots_path)

# ### Part B: Run MOD-WET Model

# # B1. Define input and output file paths
# output_filepath = REPO_ROOT / f"data/model_output/{watershed_name}/simulation_results.nc"

# # B2. Initialize the model
# print("Initializing MOD-WET model...")
# model = MODWETModel(basin_data_path=basin_data_path, met_forcing_path=met_forcing_path)

# # B3. Execute full simulation and export NetCDF results
# print("Starting simulation run...")
# model.run_simulation(output_filepath=output_filepath)
# print(f"\nSimulation run and export completed successfully!")

# End of Script